"""Key custody for ``mesh provision``: which keypair to write, and how it is recorded.

Split out of :mod:`meshprovision.cli.provision` for size, with no change in
behavior: choosing the keypair to send (:func:`select_keypair`), the origin
recorded for the node's own key (:func:`node_key_origin`), registering an
operator-named admin alias (:func:`register_admin_alias`), filling a
proven private key into an out-of-band-rotated record
(:func:`capture_proven_private_key`), and the operator-facing hint on an
admin-key-rotation refusal (:func:`finalize_admin_key_rotation_error`).
:mod:`meshprovision.cli.provision` imports and uses them; nothing here
imports from it, or from any other command module.

Secret hygiene: as in :mod:`meshprovision.cli.provision`, nothing here ever
prints/logs a base64 key or raw key bytes; identification always goes
through :func:`meshprovision.crypto.redact.fingerprint`.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING, Final

from meshprovision.crypto import keys as crypto_keys
from meshprovision.crypto.redact import SecretBytes, fingerprint
from meshprovision.crypto.weakkeys import DUPLICATE_KEY_REASON
from meshprovision.db import schema
from meshprovision.db.keys import KeyRecord
from meshprovision.db.schema import KeyOrigin, KeyType
from meshprovision.errors import AdminKeyRotationRefusedError, KeyMaterialError, PlanConflictError
from meshprovision.nodeid import NodeId
from meshprovision.provisioning import detect
from meshprovision.provisioning import plan as plan_mod
from meshprovision.provisioning.key_registry import adopt_canonical_ref
from meshprovision.provisioning.plan_admin_keys import KeyPlan

if TYPE_CHECKING:
    from pathlib import Path

    from meshprovision.cli.common import CliContext, DbSession

__all__ = [
    "capture_proven_private_key",
    "finalize_admin_key_rotation_error",
    "node_key_origin",
    "register_admin_alias",
    "select_keypair",
]


def select_keypair(
    change_plan: plan_mod.ChangePlan, live: detect.LiveConfig
) -> crypto_keys.KeyPair | None:
    """Choose the keypair (if any) to apply for the node's key plan.

    Args:
        change_plan: The plan being applied.
        live: The device's live-read configuration, consulted when the
            plan adopts the device's own already-existing keypair.

    Returns:
        A freshly generated keypair for ``regenerate``, the device's own
        keypair for ``adopt_device_key``, or ``None`` when the key plan
        changes nothing.

    Raises:
        PlanConflictError: If the plan wants to adopt the device's key but
            the device reported no key material.
    """
    if change_plan.key_plan.regenerate:
        keypair: crypto_keys.KeyPair | None = crypto_keys.generate_keypair()
    elif change_plan.key_plan.adopt_device_key:
        # _plan_node_keypair only sets adopt_device_key once it has confirmed
        # both are present -- this guards the type, not a real code path.
        live_public = live.security.public_key
        live_private = live.security.private_key
        if live_public is None or live_private is None:  # pragma: no cover
            raise PlanConflictError(
                "Plan wants to adopt the device's key but the device reported none",
                field="security.public_key",
            )
        keypair = crypto_keys.KeyPair(private=live_private, public=live_public)
    else:
        keypair = None
    return keypair


def node_key_origin(key_plan: KeyPlan, *, pending_recovered: bool) -> KeyOrigin:
    """Decide a node's own keypair's origin for ``persist_result``/the admin alias.

    Args:
        key_plan: The plan's key decisions.
        pending_recovered: Whether this run recovered a pending key
            regeneration -- fed by
            :attr:`~meshprovision.provisioning.plan_types.PlanInputs.pending_keypair_recovered`
            via the plan (see :mod:`meshprovision.db.pending_keys`).

    Returns:
        :attr:`~meshprovision.db.schema.KeyOrigin.GENERATED` when this
        host minted the key (``key_plan.regenerate``) or this run
        recovered a pending regeneration; otherwise
        :attr:`~meshprovision.db.schema.KeyOrigin.CAPTURED` (the
        ``key_plan.adopt_device_key`` case -- the key was read from the
        device, never generated by this host).
    """
    if key_plan.regenerate or pending_recovered:
        return KeyOrigin.GENERATED
    return KeyOrigin.CAPTURED


def register_admin_alias(
    ctx: CliContext,
    db: DbSession,
    *,
    admin_ref: str,
    node_id: NodeId,
    keypair: crypto_keys.KeyPair | None,
    node_origin: KeyOrigin,
) -> None:
    """Additionally file a node's keys under an admin alias reference.

    Used by ``mesh admin bootstrap --ref <alias>``: whatever material was
    just written for the node itself (or, when the key plan changed
    nothing, whatever material the database already holds for it) is
    copied under ``admin_ref`` too, and any stale ``observed-*`` row
    holding the same material is collapsed onto it.

    The alias rows' origin follows the material's own provenance, not a
    fixed value: when ``keypair is not None``, the same material is also
    being written to the node's own ``<node_id>_pub``/``_priv`` rows this
    run (via ``persist_result``), so the alias gets that same
    ``node_origin`` -- labeling it GENERATED only when this run actually
    generated the key, never for adopted (#7449) or otherwise-captured
    material. When ``keypair is None``, the key plan changed nothing and
    the material comes from whatever the database already holds for the
    node -- so the alias copies the existing ``<node_id>_pub`` row's own
    recorded origin via :meth:`~meshprovision.db.keys.KeyRecord.with_origin`,
    rather than guessing or reusing ``node_origin`` (which was computed
    for a key plan that did not apply here).

    Args:
        ctx: The shared CLI context.
        db: The already-open database session.
        admin_ref: The alias reference to file the keys under.
        node_id: The node whose keys are being aliased.
        keypair: The keypair just applied to the device, or ``None`` when
            the key plan changed nothing (the database's existing rows
            are used instead).
        node_origin: The origin being recorded (or already recorded) for
            the node's own keypair this run -- see :func:`node_key_origin`.
    """
    now = datetime.now(tz=UTC)
    public_material: bytes | None
    private_material: SecretBytes | None
    alias_origin: KeyOrigin | None
    if keypair is not None:
        public_material = keypair.public
        private_material = keypair.private
        alias_origin = node_origin
    else:
        material = db.keys.keypair_for(node_id.hex)
        public_material = material.public
        private_material = material.private
        existing_public = db.keys.find(schema.ref_for(node_id.hex, KeyType.ADMIN_PUBLIC))
        alias_origin = existing_public.origin if existing_public is not None else None

    if public_material is None:
        ctx.warn(f"No public key material available to register alias {admin_ref!r}; skipping.")
    else:
        # from_material's origin kwarg is required and non-Optional (every
        # ordinary call site knows a concrete value up front); alias_origin
        # may legitimately be None (an unknown-provenance existing row), so
        # construct with a placeholder and immediately correct it via
        # with_origin, the one greppable place that propagates "unknown".
        public_record = KeyRecord.from_material(
            admin_ref,
            KeyType.ADMIN_PUBLIC,
            public_material,
            origin=alias_origin or KeyOrigin.CAPTURED,
            created_ts=now,
        ).with_origin(alias_origin)
        db.keys.upsert(public_record)
        if private_material is not None:
            private_record = KeyRecord.from_material(
                admin_ref,
                KeyType.ADMIN_PRIVATE,
                private_material,
                origin=alias_origin or KeyOrigin.CAPTURED,
                created_ts=now,
            ).with_origin(alias_origin)
            db.keys.upsert(private_record)
        # This alias's material may already sit on some other node's
        # row under a synthetic observed-* ref an earlier mesh adopt
        # minted before this alias existed -- collapse it now, same
        # as mesh admin import does.
        adopt_canonical_ref(db.nodes, db.keys, material=public_material, canonical_owner=admin_ref)


def capture_proven_private_key(
    db: DbSession,
    *,
    node_id: NodeId,
    live_private_key: SecretBytes | None,
    now: datetime,
) -> tuple[str, ...]:
    """Record a device-proven private key into the database (CC-D1 Option A).

    Completes the out-of-band admin-key-rotation flow (``mesh admin import
    --overwrite``, batches #27-#30): that command only ever writes the new
    ``<hex>_pub`` row, so nothing records the device's matching private key
    until this runs on a later ``mesh provision``. It is not admin-specific
    -- it applies to any node's own ``<hex>_pub``/``_priv`` pair, matching
    what ``mesh provision``/``mesh adopt`` already record for every other
    captured key.

    "Proves" means the live-reported private key derives the database's
    recorded public key (:func:`~meshprovision.crypto.keys.public_key_matches`)
    -- only a party that already holds the matching private key can satisfy
    this, and the public key itself was set by a prior, separately-trusted
    step (an out-of-band import, or an earlier ``persist_result`` write).

    Args:
        db: The already-open database session. Writes land in the
            in-memory session only; the caller must save.
        node_id: The node whose own ``<hex>_pub``/``_priv`` pair to check.
        live_private_key: The device's live-reported private key, or
            ``None`` when the device reported none.
        now: Timestamp to record on any row written.

    Returns:
        One operator-facing line per row written, in order; empty when
        nothing was written. The caller must save, and print the lines
        only once that save has succeeded -- they say the key is recorded.
    """
    if live_private_key is None:
        return ()
    pub_record = db.keys.find(schema.ref_for(node_id.hex, KeyType.ADMIN_PUBLIC))
    if pub_record is None:
        return ()
    try:
        pub_material = pub_record.material()
        proven = crypto_keys.public_key_matches(live_private_key, pub_material)
    except KeyMaterialError:
        # Nothing to capture, and nothing to warn about: the recorded
        # public key already passed field validation when the database
        # loaded, so only a live private key that is not 32 bytes gets
        # here -- and build_plan regenerates over such a key
        # ("missing_key_material"), so persist_result has just recorded
        # the new pair and this pre-apply private key is moot.
        return ()
    if not proven:
        return ()

    recorded: list[str] = []
    if not db.keys.has_private(node_id.hex):
        db.keys.upsert(
            KeyRecord.from_material(
                node_id.hex,
                KeyType.ADMIN_PRIVATE,
                live_private_key,
                origin=KeyOrigin.CAPTURED,
                created_ts=now,
            )
        )
        recorded.append(
            f"Recorded the device's private key for {node_id.display} "
            "(proof of possession of the recorded public key)."
        )

    # Also fill any OTHER existing reference (an admin alias) holding the
    # same proven public material whose own private row is missing or
    # stale -- but never create a new alias private row that didn't
    # already exist (CC-D1 Option A / CONSISTENCY-CHECK.md #5.2).
    for alias_pub in db.keys.of_type(KeyType.ADMIN_PUBLIC):
        alias_ref = alias_pub.owner_node_id
        if alias_ref == node_id.hex or db.keys.has_private(alias_ref):
            continue
        try:
            if alias_pub.material() != pub_material:
                continue
        except KeyMaterialError:
            continue
        if db.keys.find(schema.ref_for(alias_ref, KeyType.ADMIN_PRIVATE)) is None:
            continue
        db.keys.upsert(
            KeyRecord.from_material(
                alias_ref,
                KeyType.ADMIN_PRIVATE,
                live_private_key,
                origin=KeyOrigin.CAPTURED,
                created_ts=now,
            )
        )
        recorded.append(f"Filled the stale private key recorded for alias {alias_ref!r}.")

    return tuple(recorded)


_ADMIN_KEY_ROTATION_DOC_HINT: Final[str] = (
    "meshprovision has no in-tool way to rotate an admin node's key. See the \"Rotating an "
    "admin node's key\" section of docs/security.md for the out-of-band procedure."
)


def finalize_admin_key_rotation_error(
    exc: AdminKeyRotationRefusedError, live: detect.LiveConfig, *, pending_path: Path | None = None
) -> AdminKeyRotationRefusedError:
    """Attach the operator-facing hint to an admin-key-rotation refusal.

    :mod:`meshprovision.provisioning.plan` cannot import
    :mod:`meshprovision.crypto` (see its module docstring: "digests are
    the caller's job"), so it raises :class:`AdminKeyRotationRefusedError`
    with no hint at all. This is the one place that both catches the pure
    layer's refusal and has ``live`` (and a crypto import) in scope to
    compute the redacted fingerprint the operator needs to verify the
    device by hand -- never the raw base64 key.

    Args:
        exc: The refusal :func:`~meshprovision.provisioning.plan.build_plan`
            raised, with no hint set.
        live: The device's normalized live configuration, already read by
            the caller.
        pending_path: This node's pending-keypair sidecar path (see
            :mod:`meshprovision.db.pending_keys`), consulted for the
            ``"pending_key_recovered"`` reason -- a node that became
            admin-bearing between an interrupted run and its recovery.

    Returns:
        A new :class:`AdminKeyRotationRefusedError` carrying the same
        ``reason``/``admin_refs`` plus a filled-in ``hint`` and, for the
        ``"adopt"``/``"capture"``/:data:`~meshprovision.crypto.weakkeys.
        DUPLICATE_KEY_REASON` reasons, ``reported_fingerprint``.
    """
    if exc.reason == "adopt":
        live_public = live.security.public_key
        reported_fingerprint = fingerprint(live_public) if live_public is not None else "<unknown>"
        hint = (
            f"The connected device reports a different key (fingerprint "
            f"{reported_fingerprint}) than the one recorded for this admin node. It is "
            "either a different device claiming its node id, or a genuine key loss "
            "(firmware #7449). Verify the physical device, and compare the fingerprint "
            "with the one the device itself shows. If it is genuine, register its key "
            f"with `mesh admin import --overwrite {live.node_id.hex}=<public key>` and "
            "re-run `mesh provision`."
        )
        others = ", ".join(
            ref
            for ref in exc.admin_refs
            if ref != schema.ref_for(live.node_id.hex, KeyType.ADMIN_PUBLIC)
        )
        if others:
            hint = f"{hint} Also re-import: {others}."
    elif exc.reason == DUPLICATE_KEY_REASON:
        # Checked by exact match, and before the generic CVE-2025-52464
        # branch below: DUPLICATE_KEY_REASON's own text also contains
        # that substring (it IS a CVE-2025-52464 finding), so the
        # substring check would otherwise mis-catch it and hand out the
        # wrong "upgrade firmware" hint for what is actually a cloned key.
        live_public = live.security.public_key
        reported_fingerprint = fingerprint(live_public) if live_public is not None else "<unknown>"
        hint = (
            f"The connected device's key (fingerprint {reported_fingerprint}) is shared "
            f"with another node already on file: {', '.join(exc.admin_refs)}. This is the "
            "CVE-2025-52464 vendor key-cloning failure mode -- compare the fingerprint "
            'with the one the device itself shows, and see the "Duplicate (cloned) keys" '
            "section of docs/security.md."
        )
    elif exc.reason == "capture":
        live_public = live.security.public_key
        reported_fingerprint = fingerprint(live_public) if live_public is not None else "<unknown>"
        hint = (
            f"This node has no recorded key, and the key it reports (fingerprint "
            f"{reported_fingerprint}) is already registered as {', '.join(exc.admin_refs)}. "
            "If this device is that admin, re-run as `mesh admin bootstrap --ref <REF>` "
            "naming it. Otherwise two devices may share one keypair (CVE-2025-52464 key "
            "cloning) -- compare the fingerprint with the one the device itself shows, "
            "and see docs/security.md."
        )
    elif "CVE-2025-52464" in exc.reason:
        reported_fingerprint = None
        hint = (
            "Upgrade the node's firmware to >= 2.6.11 and re-run, or follow the rotation "
            'procedure in the "Rotating an admin node\'s key" section of docs/security.md.'
        )
    elif exc.reason == "alias":
        reported_fingerprint = None
        ref = exc.admin_refs[0].removesuffix("_pub") if exc.admin_refs else "<ref>"
        hint = (
            f"{ref!r} already names a different admin key. meshprovision does not re-point "
            f"an admin ref to a new device. Bootstrap this node under a new ref "
            f"(`--ref <NEW>`), add it to `admin_nodes`, and retire {ref!r} per "
            'docs/security.md -> "Rotating an admin node\'s key". Or, if '
            f"{ref!r} must name this device's key, verify it and use "
            "`mesh admin import --overwrite`."
        )
    elif exc.reason == "pending_key_recovered":
        # Edge case: this node became admin-bearing between an earlier
        # interrupted regenerate and this run's recovery of its pending
        # keypair. The device's key genuinely matches the pending file --
        # this is not a #7449/impostor situation -- but S1 still refuses,
        # since the key is about to be (re)recorded on an admin-bearing
        # node with no operator-verified out-of-band step.
        reported_fingerprint = None
        hint = (
            "The connected device's key matches a keypair saved locally by an earlier "
            f"interrupted `mesh provision` run (at {pending_path}), but this node now backs "
            f"authorized admin key(s): {', '.join(exc.admin_refs)}. It was not recorded. "
            f"{_ADMIN_KEY_ROTATION_DOC_HINT}"
        )
    else:
        reported_fingerprint = None
        hint = _ADMIN_KEY_ROTATION_DOC_HINT

    return AdminKeyRotationRefusedError(
        exc.message,
        reason=exc.reason,
        admin_refs=exc.admin_refs,
        reported_fingerprint=reported_fingerprint,
        hint=hint,
    )
