"""The node-key, lockdown and security-section planners behind ``build_plan``.

Split out of :mod:`meshprovision.provisioning.plan` for size, with no change in
behavior, and bound by the same purity contract (see that module's docstring):
pure functions of :class:`~meshprovision.provisioning.plan_types.PlanInputs`,
no I/O, no clock reads, and no import of :mod:`meshprovision.crypto`. It
imports only the standard library plus :mod:`meshprovision.errors`,
:mod:`meshprovision.firmware`, :mod:`meshprovision.provisioning.detect`,
:mod:`~meshprovision.provisioning.plan_admin_keys`,
:mod:`~meshprovision.provisioning.plan_types` and
:mod:`~meshprovision.provisioning.plan_warnings`.
:func:`plan_node_keypair` decides the node keypair, :func:`evaluate_lockdown`
gates ``security.is_managed``, :func:`plan_security_section` diffs the
``security`` section, and :func:`packet_signature_policy_warning` flags a
``packet_signature_policy`` older firmware would silently drop.
"""

from __future__ import annotations

from types import MappingProxyType
from typing import Final

from meshprovision.errors import AdminKeyRotationRefusedError, LockdownRefusedError
from meshprovision.firmware import parse_firmware_version
from meshprovision.provisioning import detect
from meshprovision.provisioning.plan_admin_keys import KeyPlan
from meshprovision.provisioning.plan_types import (
    FieldChange,
    LockdownDecision,
    LockdownReason,
    PlanInputs,
    SectionChange,
    values_equal,
)
from meshprovision.provisioning.plan_warnings import PlanWarning, PlanWarningCode

__all__ = [
    "evaluate_lockdown",
    "packet_signature_policy_warning",
    "plan_node_keypair",
    "plan_security_section",
]


_PACKET_SIGNATURE_POLICY_MIN_FIRMWARE: Final[tuple[int, int, int]] = (2, 8, 0)
"""First firmware version whose ``Config.SecurityConfig`` has ``packet_signature_policy``.

Older firmware's decoder drops the unknown field, so a write is silently
lost and read-back keeps reporting the default -- see
:func:`_firmware_supports_packet_signature_policy`."""


def plan_node_keypair(inputs: PlanInputs) -> tuple[bool, str, bool, tuple[PlanWarning, ...]]:
    """Decide whether to regenerate the node keypair, or adopt the device's (step 7).

    Args:
        inputs: The plan inputs.

    Returns:
        A 4-tuple: whether to regenerate, the regenerate reason (empty
        when not regenerating), whether to adopt the device's reported
        public key into the database instead, and any
        ``"device_key_differs_from_db"``/``"pending_key_recovered"``
        warning.

    Raises:
        AdminKeyRotationRefusedError: If the decision would regenerate or
            adopt this node's key while
            :attr:`~meshprovision.provisioning.plan_types.PlanInputs.node_key_admin_refs`
            is non-empty -- i.e. the node's currently-recorded key backs an
            authorized admin key somewhere in the fleet. There is no flag
            that overrides this (see the class docstring); a legitimate
            rotation goes through the out-of-band ``mesh admin import
            --overwrite`` flow instead. This raise happens here, inside
            :func:`build_plan`, so it always precedes ``render_plan``,
            ``ctx.confirm``, ``--dry-run``'s output, the BLE PIN, and any
            device I/O -- nothing is ever written to the device or the
            database on this path. When the node has no recorded key at all
            (a first capture) and the live key is already registered
            elsewhere, ``reason`` is ``"capture"`` rather than ``"adopt"``.
    """
    live_sec = inputs.live.security
    regenerate: bool
    reason: str
    adopt: bool
    warnings: tuple[PlanWarning, ...]

    if inputs.force_regenerate_key:
        regenerate, reason, adopt, warnings = True, "forced", False, ()
    elif inputs.state is detect.NodeState.FACTORY:
        regenerate, reason, adopt, warnings = (
            True,
            "factory_key_presumed_compromised",
            False,
            (),
        )
    elif not live_sec.has_public_key or not live_sec.has_private_key:
        regenerate, reason, adopt, warnings = True, "missing_key_material", False, ()
    elif inputs.node_key_compromised:
        regenerate, reason, adopt, warnings = (
            True,
            inputs.node_key_reason or "weak_key_audit",
            False,
            (),
        )
    elif inputs.pending_keypair_recovered:
        regenerate, reason, adopt = False, "pending_key_recovered", True
        warnings = (
            PlanWarning(
                PlanWarningCode.PENDING_KEY_RECOVERED,
                "Recording the keypair generated by an interrupted `mesh provision` run, "
                "recovered from its pending-keypair file.",
                section="security",
                field="public_key",
            ),
        )
    elif inputs.db_public_key is not None and inputs.db_public_key != live_sec.public_key:
        regenerate, reason, adopt = False, "", True
        warnings = (
            PlanWarning(
                PlanWarningCode.DEVICE_KEY_DIFFERS_FROM_DB,
                "The device's reported public key differs from the Keys sheet; adopting the "
                "device's key rather than overwriting it (firmware issue #7449).",
                section="security",
                field="public_key",
            ),
        )
    elif inputs.db_public_key is None:
        regenerate, reason, adopt, warnings = False, "", True, ()
    else:
        regenerate, reason, adopt, warnings = False, "", False, ()

    first_capture = adopt and inputs.db_public_key is None and not inputs.pending_keypair_recovered
    if (regenerate or adopt) and inputs.node_key_admin_refs:
        if first_capture:
            message = (
                f"{inputs.live.node_id.display} has no recorded key, and the key it reports "
                f"is already registered as: {', '.join(inputs.node_key_admin_refs)}."
            )
        else:
            message = (
                f"{inputs.live.node_id.display}'s key would change while it backs authorized "
                f"admin key(s): {', '.join(inputs.node_key_admin_refs)}."
            )
        raise AdminKeyRotationRefusedError(
            message,
            # reason is already the right label for every branch above
            # (including "pending_key_recovered"), except the plain #7449
            # adopt branch, which leaves it "" -- fall back to "adopt" only
            # there. The new first-capture branch also leaves it "" but
            # needs its own distinct label.
            reason="capture" if first_capture else (reason or "adopt"),
            admin_refs=inputs.node_key_admin_refs,
        )

    return regenerate, reason, adopt, warnings


def evaluate_lockdown(
    inputs: PlanInputs, desired_admin_keys: tuple[bytes, ...]
) -> LockdownDecision:
    """Decide whether ``security.is_managed`` may be enabled (step 9).

    Args:
        inputs: The plan inputs.
        desired_admin_keys: The desired admin-key set computed by
            :func:`meshprovision.provisioning.plan_admin_keys.plan_admin_key_material`.

    Returns:
        The :class:`LockdownDecision`.

    Raises:
        LockdownRefusedError: If the template opts into ``is_managed``
            but zero admin keys would be authorized, any authorized key's
            private counterpart does not correspond to its public key,
            none of the authorized keys has its private counterpart on
            hand, or any authorized key fails the weak-key audit. These
            are hard refusals: they are the "lock yourself out" and "lock
            with a compromised key" cases. The weak-key audit is checked
            first, so a key that is both compromised and mismatched is
            reported as ``"weak_admin_key"``.

    Note:
        ``--allow-lockdown`` gates only the *disabled -> enabled*
        transition. When the live device is already locked down
        (``inputs.live.security.is_managed`` is ``True``) and every
        hard gate above still passes, this returns ``enable=True``
        regardless of ``inputs.allow_lockdown`` -- an operator who
        forgets to repeat ``--allow-lockdown`` on a later, unrelated
        re-run must never have this function plan to *disable* an
        admin lockdown that was deliberately enabled earlier.
    """
    if not inputs.template.security.is_managed:
        gates = MappingProxyType(
            {
                "has_admin_keys": bool(desired_admin_keys),
                "has_private_counterpart": any(k.has_private for k in inputs.admin_keys),
                "audit_clean": all(k.audit_ok for k in inputs.admin_keys),
                "explicit_intent": inputs.allow_lockdown,
            }
        )
        return LockdownDecision(enable=False, reason=LockdownReason.TEMPLATE_OPT_OUT, gates=gates)

    # Must precede the emptiness gate below: a fully compromised admin_nodes list
    # filters down to desired_admin_keys == () in plan_admin_keys.plan_admin_key_material, which
    # would otherwise be refused as "no_admin_keys" and hide the real cause. This
    # reads the unfiltered inputs.admin_keys for exactly that reason.
    weak_refs = tuple(k.key_ref for k in inputs.admin_keys if not k.audit_ok)
    if weak_refs:
        raise LockdownRefusedError(
            f"Authorized admin key(s) failed the weak-key audit: {', '.join(weak_refs)}.",
            reason="weak_admin_key",
            hint="Replace the offending key(s) (see `mesh admin import`) and re-run.",
        )
    if not desired_admin_keys:
        raise LockdownRefusedError(
            "is_managed=true with zero authorized admin keys would lock the node with "
            "nobody able to administer it.",
            reason="no_admin_keys",
            hint=(
                "Add 1-3 refs to admin_nodes and register them with `mesh admin bootstrap` "
                "/ `mesh admin import`, or set security.is_managed to false."
            ),
        )
    mismatched = tuple(k.key_ref for k in inputs.admin_keys if k.private_mismatch)
    if mismatched:
        raise LockdownRefusedError(
            f"Admin key(s) have a private counterpart that does not match the "
            f"registered public key: {', '.join(mismatched)}.",
            reason="private_key_mismatch",
            hint=(
                "The _priv row exists but derives a different public key -- most often a "
                "half-finished rotation or a paste from another admin's backup. Correct "
                "the _priv value (or re-run `mesh admin bootstrap`) before locking down."
            ),
        )
    if not any(k.has_private for k in inputs.admin_keys):
        raise LockdownRefusedError(
            "None of the authorized admin keys has its private counterpart in the Keys sheet.",
            reason="no_private_counterpart",
            hint=(
                "At least one authorized admin key must have its private counterpart in "
                "the Keys sheet."
            ),
        )
    gates = MappingProxyType(
        {
            "has_admin_keys": True,
            "has_private_counterpart": True,
            "audit_clean": True,
            "explicit_intent": inputs.allow_lockdown,
        }
    )
    if not inputs.allow_lockdown:
        if inputs.live.security.is_managed:
            return LockdownDecision(enable=True, reason=LockdownReason.ALREADY_LOCKED, gates=gates)
        return LockdownDecision(
            enable=False, reason=LockdownReason.ALLOW_LOCKDOWN_NOT_SET, gates=gates
        )
    return LockdownDecision(enable=True, reason=LockdownReason.AUTHORIZED, gates=gates)


def _firmware_supports_packet_signature_policy(firmware_version: str) -> bool:
    """Whether a device's firmware is known to carry ``packet_signature_policy``.

    Conservative: an empty or unparseable version counts as unsupported,
    since writing the field to firmware without it can never be verified
    (read-back keeps the default), which leaves the node unrecordable and
    replans the same change on every run.

    Args:
        firmware_version: The live firmware version string.

    Returns:
        ``True`` only for a parseable version ``>= 2.8.0``.
    """
    parsed = parse_firmware_version(firmware_version)
    return parsed is not None and parsed >= _PACKET_SIGNATURE_POLICY_MIN_FIRMWARE


def packet_signature_policy_warning(inputs: PlanInputs) -> PlanWarning | None:
    """Warn when a templated ``packet_signature_policy`` change was skipped for firmware.

    Silent when the template leaves the field unset, when the live value
    already matches (so a ``COMPATIBLE`` template on pre-2.8 firmware, which
    always reads back as the ``COMPATIBLE`` default, never warns), or when
    the firmware supports the field.

    Args:
        inputs: The plan inputs.

    Returns:
        A ``field_unsupported_by_firmware`` :class:`PlanWarning`, or ``None``.
    """
    desired = inputs.template.security.packet_signature_policy
    current = inputs.live.security.packet_signature_policy
    firmware = inputs.live.firmware_version
    if (
        desired is None
        or values_equal(current, desired)
        or _firmware_supports_packet_signature_policy(firmware)
    ):
        return None
    if not firmware.strip():
        reason = "the device reported no firmware version"
    elif parse_firmware_version(firmware) is None:
        reason = f"firmware version {firmware!r} could not be parsed"
    else:
        reason = f"firmware {firmware!r} predates 2.8"
    return PlanWarning(
        PlanWarningCode.FIELD_UNSUPPORTED_BY_FIRMWARE,
        f"security.packet_signature_policy not changed ({current} -> {desired}): {reason}, "
        "and only firmware 2.8+ has this field, so the write could never be verified. "
        "Upgrade the firmware, or remove packet_signature_policy from the template.",
        section="security",
        field="packet_signature_policy",
    )


def plan_security_section(
    inputs: PlanInputs, key_plan: KeyPlan, lockdown: LockdownDecision
) -> SectionChange | None:
    """Diff the ``security`` scalar fields and fold in pending key writes (step 8).

    Args:
        inputs: The plan inputs.
        key_plan: The already-decided key plan.
        lockdown: The already-decided lockdown decision.

    Returns:
        ``None`` when neither a scalar field nor any key material needs
        writing. Otherwise a ``"security"`` :class:`SectionChange` with
        ``reboots_device=True`` -- included even with an empty
        ``changes`` tuple when only key material (never represented as
        a :class:`FieldChange`) needs writing, since
        :mod:`meshprovision.provisioning.apply` only writes a section
        that is present in :attr:`~meshprovision.provisioning.plan_types.ChangePlan.sections`.
        ``packet_signature_policy`` is only diffed when
        :func:`_firmware_supports_packet_signature_policy` passes;
        :func:`packet_signature_policy_warning` reports a change skipped
        that way.
    """
    live_sec = inputs.live.security
    template_sec = inputs.template.security

    desired: dict[str, bool | str] = {"admin_channel_enabled": False}
    current: dict[str, bool | str | None] = {
        "admin_channel_enabled": live_sec.admin_channel_enabled
    }

    if template_sec.serial_enabled is not None:
        desired["serial_enabled"] = template_sec.serial_enabled
        current["serial_enabled"] = live_sec.serial_enabled
    if template_sec.debug_log_api_enabled is not None:
        desired["debug_log_api_enabled"] = template_sec.debug_log_api_enabled
        current["debug_log_api_enabled"] = live_sec.debug_log_api_enabled
    if template_sec.packet_signature_policy is not None and (
        _firmware_supports_packet_signature_policy(inputs.live.firmware_version)
    ):
        desired["packet_signature_policy"] = template_sec.packet_signature_policy
        current["packet_signature_policy"] = live_sec.packet_signature_policy

    desired["is_managed"] = lockdown.enable
    current["is_managed"] = live_sec.is_managed

    changes: list[FieldChange] = []
    for field_name, desired_value in desired.items():
        current_value = current[field_name]
        if not values_equal(current_value, desired_value):
            reason = "forced" if field_name == "admin_channel_enabled" else "template"
            changes.append(
                FieldChange(
                    section="security",
                    field=field_name,
                    current=current_value,
                    desired=desired_value,
                    reason=reason,
                )
            )

    # adopt_device_key alone must NOT pull in the security section: it's a
    # database-side decision (record the device's own reported key instead
    # of overwriting it) that write_section has no branch for, so an
    # adopt-only plan would otherwise issue a zero-field writeConfig(
    # "security") for nothing -- exactly the write firmware issue #7449
    # says can silently discard the key this plan exists to preserve.
    # KeyPlan.is_empty deliberately still counts adopt_device_key (the run
    # still has work to do), so it can't be used as this section's gate.
    needs_device_write = key_plan.regenerate or key_plan.change_admin_keys
    if not changes and not needs_device_write:
        return None
    return SectionChange(
        section="security",
        kind=inputs.live.kind_of("security"),
        changes=tuple(changes),
        reboots_device=True,
    )
